<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8" />
<title>Terranova_design</title>
<script data-ad-client="ca-pub-7614541669024341" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
</head>
<body>
- name: Jekyll Action
  uses: helaili/jekyll-action@1.0
border="1"
align="center"
rules="rows"
style="width:60%;"
<table
border="1"
align="center"
rules="rows"
style="width:60%;">
<tr>
<td>
border="1"
background="violet.jpeg"
cellpadding="10"
style="width:100%; border-radius:5px;"
<tr>
<th>
<h1>Terranova</h1>
<h3>site for disigner company</h3>
</th>
</tr>
</table>
<table
border="1"
bgcolor="#e6e6fa"
cellpadding="10"
style="width:100%; border-radius:5px;">
<tr>
rowspan="2"
style="width:80%"
<td
rowspan="2"
style="width:80%">
<h2>Страница</h2>
<p style="text-indent:20px">
WHATCH ME.</p>

<p style="text-indent:20px">SELL YOUR FREE TIME.</p>
</td>
<td bgcolor="#e6e6fa">
<h3>Меню</h3>
<p>
<a href="">
<img src="http://trueimages.ru/img/00/06/f4fffdb5.png">
style="margin-left:5px;"
<span style="margin-left:5px;">Страница</span></a>
</p>
<p>
<a href="">
<img src="http://trueimages.ru/img/31/ab/4dcb087c2ae4305edcd15171696.jpg">
<span style="margin-left:5px;">Страница 1</span;></a>
</p>
<p>
<a href="">
<img src="http://trueimages.ru/img/31/ab/4dcb087c2ae4305edcd15171696.jpg">
<span style="margin-left:5px;">Страница 2</span></a>
</p>
</td>
</tr>
<tr>
<td
bgcolor="#e6e6fa"
align="center">
<h3>Общая информация</h3>
<p>Текст общей информации</p>
</td>
</tr>
</table>
<table
border="1"
bgcolor="#7FFFD4"
height="100"
cellpadding="10"
style="width:100%; border-radius:5px;">
<tr>
<th>
<h3>Подвал</h3>
</th>
</tr>
</table>
</td>
</tr>
</table>
</body>
</html>
